<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Properties\launchSettings.json" />
    <Compile Include="HostFactory.fs" />
    <Compile Include="Assertions.fs" />
    <Compile Include="TestUtilities.fs" />
    <Compile Include="TestsBase.fs" />
    <Compile Include="Db\EventRepositoryTests.fs" />
    <Compile Include="Db\GameRepositoryTests.fs" />
    <Compile Include="Db\PlayerRepositoryTests.fs" />
    <Compile Include="Db\SearchRepositoryTests.fs" />
    <Compile Include="Db\UserRepositoryTests.fs" />
    <Compile Include="Logic\EventServiceTests\EventServiceTests.fs" />
    <Compile Include="Logic\GameCrudServiceTests\GetUpdateGameParametersEventTests.fs" />
    <Compile Include="Logic\GameManager\AddPlayerTests.fs" />
    <Compile Include="Logic\GameManager\CreateGameTests.fs" />
    <Compile Include="Logic\GameManager\GetGameTests.fs" />
    <Compile Include="Logic\GameManager\RemovePlayerTests.fs" />
    <Compile Include="Logic\GameManager\SelectCellTests.fs" />
    <Compile Include="Logic\GameManager\StartGameTests.fs" />
    <Compile Include="Logic\GameStartService\GetGameStartEventsTests.fs" />
    <Compile Include="Logic\GameStartService\GameStartServiceTests.fs" />
    <Compile Include="Logic\PlayerService\FillEmptyPlayerSlotsTests.fs" />
    <Compile Include="Logic\PlayerService\GetAddPlayerEventTests.fs" />
    <Compile Include="Logic\PlayerService\GetRemovePlayerEventTests.fs" />
    <Compile Include="Logic\SearchManager\SearchGamesTests.fs" />
    <Compile Include="Logic\SessionService\CloseSessionTests.fs" />
    <Compile Include="Logic\SessionService\CreateSessionTests.fs" />
    <Compile Include="Logic\SessionService\GetAndRenewSessionTests.fs" />
    <Compile Include="Logic\TurnService\CommitTurnTests.fs" />
    <Compile Include="Logic\TurnService\ResetTurnTests.fs" />
    <Compile Include="Logic\UserManager\CreateUserTests.fs" />
    <Compile Include="Logic\UserManager\DeleteUserTests.fs" />
    <Compile Include="Logic\UserManager\GetUserTests.fs" />
  </ItemGroup>
  <ItemGroup>
	<PackageReference Include="FSharp.Core" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\api.common\api.common.fsproj" />
    <ProjectReference Include="..\..\api.db\api.db.fsproj" />
    <ProjectReference Include="..\..\api.enums\api.enums.fsproj" />
    <ProjectReference Include="..\..\api.logic\api.logic.fsproj" />
    <ProjectReference Include="..\..\api.model\api.model.fsproj" />
  </ItemGroup>
</Project>