<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Logic\Managers\UserManagerTests\CreateUserTests.fs" />
    <Compile Include="Logic\Services\EncryptionServiceTests.fs" />
    <Compile Include="BoardModelExtensionTests.fs" />
    <Compile Include="Logic\Services\SessionServiceTests\OpenSessionTests.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FakeItEasy" />
	<PackageReference Include="FSharp.Core" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\api.common\api.common.fsproj" />
    <ProjectReference Include="..\..\api.db.interfaces\api.db.interfaces.fsproj" />
    <ProjectReference Include="..\..\api.enums\api.enums.fsproj" />
    <ProjectReference Include="..\..\api.logic.interfaces\api.logic.interfaces.fsproj" />
    <ProjectReference Include="..\..\api.logic\api.logic.fsproj" />
    <ProjectReference Include="..\..\api.model\api.model.fsproj" />
  </ItemGroup>
</Project>